language: node_js
node_js:
  - "stable"
services:
  - postgresql          
env:
  global:
  - DB_USERNAME=postgres
  - DB_PASSWORD=postgres
  - DB_HOST=127.0.0.1
  - TEST_DATABASE=test_db
  - SECRET=a7qsdtbwecawq
  - EMAIL=goodfellascohort40@gmail.com
  - EMAIL_PASSWORD=andela_cohort40
  - CLOUD_NAME="drmmqcxkc"
  - CLOUD_APIKEY="657175248381499"
  - CLOUD_APISECRET="CRyA-b_t63WwPxDuWJZUCRCiz9E"
before_script:
  - npm install
  - psql -c 'drop database if exists test_db;' -U postgres
  - psql -c 'create database test_db;' -U postgres
  - sequelize db:migrate --env test
script:
  - npm test
after_script:
  - npm run coverage
